"""Add user_name field to users table

Revision ID: 1ab4da1bc43a
Revises: 7e7ba32a0424
Create Date: 2026-01-20 22:31:13.329498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab4da1bc43a'
down_revision = '7e7ba32a0424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
